name: schmitt
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  animations:
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  bubble:
  easy_localization: ^3.0.0
  flutter_phoenix: ^1.0.0
  shared_preferences: ^2.0.13
  image_picker: ^0.8.7+5
  firebase_core: 
  cloud_firestore: 
  firebase_storage: 
  firebase_auth:
  google_sign_in: 
  flutter_facebook_auth:
  flutter_svg: ^2.0.9
  intl_phone_field: ^3.1.0
  expandable_text: 
  video_player: ^2.4.9
  csc_picker: ^0.2.7
  pin_code_fields: 
  uuid:
  swipe_to:
  audio_waveforms: 
  audioplayers:
  image_cropper: 
  camera: ^0.10.1
  permission_handler:
  country_picker: ^2.0.24
  firebase_messaging: ^14.7.15
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_animations: ^1.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.svg"

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700